:PROPERTIES:
:CATEGORY: notebook
:ID:       37f7537c-ec09-4212-bc93-b6d8d90dd63a
:END:
#+STARTUP: overview indent
#+OPTIONS: toc:2

* Installation

The repo allows you train an active inference agent in a discrete, grid-world, custom environment, created using Gymnasium (https://gymnasium.farama.org/), a regularly maintained fork of Open AI's Gym library (which is no longer maintained).

Instruction to install the required packages and visit the Active Inference Zoo. This guide assumes that the user
has installed Python through Anaconda or similar distributions.

1. Sit back and relax, ideally with your favourite beverage and/or snack.

2. Clone the Github repository (say, with Github Desktop) or download it into your favourite local folder.

3. Open an Anaconda Prompt and go to the folder where you downloaded the files (using cd command).

4. Create a conda environment and install requirements either using pip or conda:

	4a. If you use pip, first create the environment with conda:

		`> conda create -n myenv`

	or

		`> conda create --prefix <path to your environment>`

	then,

		`> pip install -r requirements.txt`

	4b. If you use conda, create the environment and install the packages at the same time with:

		`> conda env create -n <name you picked> -f /path/to/aiz.yml`

	or,

		`> conda env create -p <path to your environment> -f /path/to/aiz.yml`

5. Activate your environment with:

	`> conda activate <environment name>`

or,

	`> conda activate /path/to/your_environment`

6. Change directory (cd command) to `~/your_environment/discrete_sas/o_maze`.

7. Run the main Python script by typing:

	`> python main_ai_exp0.py`

8. Hope for the best and keep your fingers crossed.


For more info on managing conda environments visit the official documentation at:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html


Please contact me at ft98@sussex.ac.uk or filippo.torresan@gmail.com, if:

	- Preparing for your visit to the Active Inference Zoo appears to be impossible;
	- Entering the zoo turns out to be more difficult than what the above guide suggests;
	- Visiting the zoo led you to a state of confusion;
	- You have encountered improbable beings;
	- After the visit, your free energy/expected free energy was not minimised;
	- Any other compelling issue.

* Overview of the Repository

The core script is ~../scripts/main.py~ which defines an argument parser and passes the arguments provided through the command line to the train function of a task (Python) module defined in ~../active_inf/tasks/~ to train an agent; the task module is inmported dynamically depending on the task name the user has provided through the command line (see [[How to Run an Experiment]]).

* How to Run an Experiment

To run a script using the =active_inf= module write in a terminal:

~python -m scripts.main -task task1 -env GridWorldv0 -nr 1 -ne 2 -pt states -as kd~

To visualize the data:

~python -m active_inf.visuals.visualiz -i 4 -v 8 -ti 0 -tv 8 -vl 3 -hl 3~

# Tests

Running some test in the toy grid world and jotting down some observation to check that everything works as expected.

- *Test 1*: Learning State Observation Mapping (matrix A) with Knowledge of State-Transitions (matrix B)

IMPORTANT: this test was run with high preferences over every single state of the optimal trajectory (full reward) as opposed to a single high preference over the goal state (sparse reward).

Test ran using the following command:

~python -m scripts.main -task task1 -env GridWorldv0 -nr 1 -ne 50 -pt states -as kd -lA -nvs 5~

So, we are training the agent for 50 episodes and we require it to learn the state-observation mapping (A matrix) using the ~-lA~ flag.

* Resources
* References
